### ISSUE TITLE
is vuejs 2 supported?

### ISSUE THREAD

**Issue by molaie** [FranzSkuffka/vue-medium-editor#1]
in vue-awesome it is said that this supports vuejs 2, but it seems that vue 1 is supported.
at least, when i 

> npm install vue-medium-editor

in nod modules folder, it is obviously base on vuejs 1.

**Comment by janwirth** [comment]
currently not, in fact I had a module for vue2 in the pipeline but then hardware issues got in the way.

OFC, contributions are welcome.

**Comment by janwirth** [comment]
Check out [2.0](https://github.com/FranzSkuffka/vue-medium-editor/tree/2.0), 48175421ed0b1a8e657dfb0771fb2237555d99e2 :)

Enjoy, my friend. Hope this helps.
Going to publish it to the NPM registry now.
