### ISSUE TITLE
Unexpected token import?

### ISSUE THREAD

**Issue by AeonFr** [FranzSkuffka/vue-medium-editor#12]
After following the installation steps listed in the README file, I get the error: Uncaught SyntaxError: Unexpected token import. This error does not appear on compilation, but on runtime, meaning that the console shows nothing but when I open localhost I get a blank screen, and I see that error on the console.

I understand this issue is related with webpack and the ES2015 syntax, but I can't figure out what to do to fix it! Any help is appreciated :)

![unexpected-token-import](https://cloud.githubusercontent.com/assets/11742754/21570916/1849f4a8-cea9-11e6-866c-78a70b2b3813.png)

This is my app.js
```
import editor from 'vue2-medium-editor'
import Vue from 'vue'
import App from './App'
import VueRouter from 'vue-router'
Vue.use(VueRouter)

const randomIMG = Vue.component('random-img', require('./components/randomIMG'))
const mercadolibre = Vue.component('mercadolibre', require('./components/mercadolibre'))

const router = new VueRouter({
	routes: [
		{ path: '/', component: randomIMG },
		{ path: '/mercadolibre', component: mercadolibre },
	]
})

window._ = require('lodash')
window.store = require('./store/store.js')

new Vue({
	el: '#app',
	store,
	router,
	render: h => h(App),
	components: {
		'medium-editor': editor
	}
})
```

**Comment by AeonFr** [comment]
I realized I have the runtime version of Vue in my proyect, so I can't render templates from strings, only from vue files. So even if this problem would be solved, I could not be able to use the library anyways (at least for my proyect). I exported the contents of the `medium-editor.js` file in this proyect to a `.vue` file and uploaded to a Gist. Now the editor works as expected.

In case someone else needs it, here's the gist:

https://gist.github.com/AeonFr/5c0992fe678800922687818b1b7ce41d

**Comment by janwirth** [comment]
If you like, you can add it to the wiki.

Also, do you think the .vue component should include the base CSS?

**Comment by AeonFr** [comment]
I didn't include it in case someone wants to use it twice in the same page,
but I havent tested  including it twice. Maybe it should, on the worst case
scenario the same stylesheet would be included twice but the browser would
download it once anyway
