### ISSUE TITLE
Demo Page

### ISSUE THREAD

**Issue by janwirth** [FranzSkuffka/vue-medium-editor#14]
Vue-Medium Editor needs a demo site.

I build one already but it needs some polishing. Currently not public.

A site that shares design with the medium-editor demo page would be great. RawGit may be used to get the original CSS to extend it with few styles inside style tags.

**Comment by franz-josef-kaiser** [comment]
How about an `git checkout --orphan gh-pages` branch? Push there and people can jump in.

**Comment by janwirth** [comment]
Good point. Hope you like it.

https://franzskuffka.github.io/vue-medium-editor/

Closed by 78c9d12fa5505d0035ac9a8e2925f46f0a7f7036
