### ISSUE TITLE
Importing gives "module not found" error

### ISSUE THREAD

**Issue by tonila** [FranzSkuffka/vue-medium-editor#18]
When importing as specified in the readme: `import editor from 'vue2-medium-editor'` Webpack build returns error: `Module not found: Error: Can't resolve 'vue2-medium-editor'`

I had to change it to `import editor from 'vue2-medium-editor/vue-medium-editor'` to make it work.

**Comment by janwirth** [comment]
Okay strange I will look into it. Probably has to do with the package.json. do you have a repo for reproduction?

**Comment by BenOvermyer** [comment]
I have the same problem.

I'm building an application on Laravel; it uses Laravel Mix to include Vue, and I'm building everything with `yarn`. Bootstrapping via:

```
window._ = require( 'lodash' );
window.Vue = require( 'vue' );
window.axios = require( 'axios' );

import editor from 'vue2-medium-editor';

window.axios.defaults.headers.common = {
    'X-Requested-With': 'XMLHttpRequest'
};
```

If I change it as tonila did, it works.

**Comment by janwirth** [comment]
Okey so I found the bug: The package.json was misconfigured, pointing at `medium-editor.js` which just does not exist.

**Comment by janwirth** [comment]
Please check whether the issue persists and come back at me if it does.

Thank you guys for contributing.
