### ISSUE TITLE
adding medium editor as dependency

### ISSUE THREAD

**Issue by molaie** [FranzSkuffka/vue-medium-editor#2]
isn't it good idea to add medium editor as a direct dependency?

**Comment by janwirth** [comment]
Sure, thank you for your feedback :)

If you take a close look, you will see the dependency defined here: https://github.com/FranzSkuffka/vue-medium-editor/blob/1.0/package.json#L27

**Comment by janwirth** [comment]
Or am I mistaken? Please clarify if I am missing something.

**Comment by molaie** [comment]
Yes, i didn't saw that. you are right.
