### ISSUE TITLE
Also pass caret index in edit event.

### ISSUE THREAD

**Issue by alfredobarron** [FranzSkuffka/vue-medium-editor#22]

**Comment by janwirth** [comment]
Can you please elaborate?

**Comment by alfredobarron** [comment]
```
<medium-editor :text="item.title"  v-on:edit="update(text, item.index)"></medium-editor>


update: function (text, index) {
    console.log(text);
    console.log(index);
}
```

**Comment by janwirth** [comment]
This should not be too complicated. Can you create a PR?

**Comment by alfredobarron** [comment]
I don't have idea how to do.

**Comment by janwirth** [comment]
Here is a great tutorial on pull requests.
https://yangsu.github.io/pull-request-tutorial/

**Comment by janwirth** [comment]
@alfredobarron If I understand correctly, you also wish to receive the current caret index during the edit event. Is that correct?

My thoughts are the following: This is a quite specific use case. The API of MediumEditor is quite exhaustive. I did not see a concrete API section that would allow to pass the current caret position. If this is what you need, you should create an issue over at https://github.com/yabwe/medium-editor and link it to this one.

Generally, I think the API of vue-medium-editor could be extended nicely if we would just pass the element with each `edit` event. Like this any user can react to changes in whatever way they desire.

As this is currently the only issue requesting such a feature I will close it soon. However, if you still need help we can work on this together.

Reference:
https://github.com/yabwe/medium-editor/blob/master/API.md

**Comment by janwirth** [comment]
Please see: https://github.com/yabwe/medium-editor/issues/730 for viewing or manipulating selections.
