### ISSUE TITLE
How to integrate with medium-editor-markdown?

### ISSUE THREAD

**Issue by javisperez** [FranzSkuffka/vue-medium-editor#26]
Hello, first of all, nice plugin, thank you!

Second, I'm looking to integrate this with this plugin: https://github.com/IonicaBizau/medium-editor-markdown which incorporates markdown instead of HTML, is there any way I can use that plugin with Vue-medium-editor? Thanks

**Comment by janwirth** [comment]
I think this is not possible without touching the source code.

**Comment by javisperez** [comment]
Hey yeah, thank you for your answer, i was able to do it with the options :D just passed the plugin as an option, so I'm closing this as i got it working now, sorry for not closing it before, i completely forgot about it.

**Comment by janwirth** [comment]
Ok, glad to hear you got it sorted out as this plugin covers your case :).

Having a closed issue can be useful for helping other people finding their way around :)
