### ISSUE TITLE
Editor does not emit edit event when all text is deleted

### ISSUE THREAD

**Issue by behlers** [FranzSkuffka/vue-medium-editor#29]
Hi there,
just wanted to know, is this a bug or a feature.
Because of this: 
```this.$refs.element.addEventListener('DOMSubtreeModified', () => {
      if (this.$refs.element.childNodes[0]) {
        this.$emit('edit', this.$refs.element.innerHTML)
      }
```
Line 59 following, the edit event is not called when the whole text is deleted.
If that is something that is supposed to happen I will have to build a work around myself, but in that case a delete event might be useful.

**Comment by janwirth** [comment]
Actually, this is intended. When deleting the entire content, medium-editor re-inserts some new content and I had some strange side effects.

After deleting the entire content, the editor submits an update that contains `<br>`. You can try it out on the demo page. https://franzskuffka.github.io/vue-medium-editor/

I am closing this now. Please let me know if you have any further issues with this so I can assist.
