### ISSUE TITLE
Use editableInput event instead of DOMSubtreeModified?

### ISSUE THREAD

**Issue by janwirth** [FranzSkuffka/vue-medium-editor#3]

**Comment by molaie** [comment]
yes, I agree, this is a reasonable choice

**Comment by janwirth** [comment]
Why do you think so? I am not entirely sure about it yet.
The implementation of `editableInput` is here:
https://github.com/yabwe/medium-editor/blob/master/src/js/events.js#L472

They are comparing the old and new innerHtml. Probably it's faster performance-wise because the editableInput event is fired anyways. Also they use caching to not fire the event in case the content did not change..

**Comment by molaie** [comment]
vue medium, should be just a simple wrapper for medium editor, not going inside internal implementation of medium editor.
That is exactly what I think. the inner implementation should be inside component(medium editor) itself. they get many feedback and their choice is the best in its class for all users. using component event and binding, is always best way of doing it.

**Comment by janwirth** [comment]
PR is welcome.

**Comment by janwirth** [comment]
@molaie I just tested it and found out that using `editableInput` instead of `DOMSubtreeModified` sends the event not specific to a certain instance of the editor. This means that coexisting instances will overwrite each other's value.

Regards
