### ISSUE TITLE
Unexpected token import

### ISSUE THREAD

**Issue by nachocab** [FranzSkuffka/vue-medium-editor#30]
In reference to #5 and #12, I also get `Unexpected token import`. It might make sense to update the Readme with these import call:

```
import editor from 'vue2-medium-editor/dist/vue-medium-editor'
```

**Comment by janwirth** [comment]
Do you know a way to automatically use the dist folder as entry point in published NPM packages? That would be the preferred solution.

**Comment by nachocab** [comment]
Yeah, I think you'd just have to change [this line](https://github.com/FranzSkuffka/vue-medium-editor/blob/master/package.json#L5) to `"main": "vue2-medium-editor/dist/vue-medium-editor.js",`
