### ISSUE TITLE
Outdated dist folder in #1.0.4

### ISSUE THREAD

**Issue by pizzot** [FranzSkuffka/vue-medium-editor#32]
The dist folder has not been update with the changes released with v1.0.4. Can this be fixed please?

**Comment by janwirth** [comment]
Closing as duplicate of #33

**Comment by pizzot** [comment]
This was mean to flag the issue with the particular version and the other one to think of a way to prevent the issue from happening in future.

Thanks

**Comment by janwirth** [comment]
I see. Can you check #31 ? I would appreciate your perspective.

**Comment by pizzot** [comment]
Sorry, was working on differnet stuff for a while. Assuming this is not relevant any more, I am having another issue: #44
