### ISSUE TITLE
Outdated dist folder

### ISSUE THREAD

**Issue by pizzot** [FranzSkuffka/vue-medium-editor#33]
Following up on #32 this seems to be a common issue with releases. Can maybe the process of updating the dist folder be automated when a new release is published? 

Sorry, I have no idea how this can be done.

**Comment by janwirth** [comment]
This can be easily achieved using scripts in the package.json

You can see it in this line here:
https://github.com/FranzSkuffka/vue-medium-editor/blob/master/package.json#L11

Will do in the next version.

**Comment by pizzot** [comment]
Thanks @FranzSkuffka, however I am unable to run this on my windows machine where my development is happening for some reason and the server not necessarily has `node` version required to run the scripts.

**Comment by janwirth** [comment]
Also I noted that for some reason the min script is not executed.
