### ISSUE TITLE
Uncaught SyntaxError: Unexpected token import

### ISSUE THREAD

**Issue by higab85** [FranzSkuffka/vue-medium-editor#35]
Hey!
I can't import the `vue2-medium-editor` as I get the syntaxerror from the title... I am using the full version of vue, not runtime.

I'm making an electron app, where the executable is `app.js`, and I'm trying to import medium-editor on a file `main.js` with `const VueMediumEditor = require('vue2-medium-editor')`. I don't understand what I'm doing wrong!

Thanks in advance :)

**Comment by janwirth** [comment]
Hey, there, sorry for the issue. This is a duplicate of #30

**Comment by higab85** [comment]
Didn't see that, sorry! Thanks
