### ISSUE TITLE
Runtime-only build of Vue

### ISSUE THREAD

**Issue by kirillbunin** [FranzSkuffka/vue-medium-editor#39]
I've tried using this but all i get is 
`(unknown) [Vue warn]: You are using the runtime-only build of Vue where the template compiler is not available. Either pre-compile the templates into render functions, or use the compiler-included build.`
and
`[Vue warn]: Error in mounted hook: "TypeError: Cannot read property 'parentNode' of undefined"`

I'm using it in one-file `.vue` components, otherwise as described on https://franzskuffka.github.io/vue-medium-editor/

**Comment by janwirth** [comment]
This will come with the next release where a render function is used. Currently I am just out of capacity.
