### ISSUE TITLE
Can't load existing Text/HTML

### ISSUE THREAD

**Issue by dsampaolo** [FranzSkuffka/vue-medium-editor#4]
Hi,

Thank you for your work. It's (oddly) very hard to find a usable WYSIWYG editor in VueJS2.

I have an issue when I try to reload a previously saved text. As medium-editor outputs HTML, it shows the code instead of rendering it.

You can solve this by replacing (in medium-editor.js, line 15) :
`template: '<div ref="element" > {{ text }} </div>',`
by :
`template: '<div ref="element" v-html="text"></div>',`

It's not fully-tested but I didn't see any caveat yet.

**Comment by janwirth** [comment]
No problem :) Glad my work helps you. Thank you very much for your report.

Bug is fixed. You can install the latest version through npm with `npm i FranzSkuffka/vue-medium-editor`.
