### ISSUE TITLE
Template or render function not defined

### ISSUE THREAD

**Issue by renatoslcdevshop** [FranzSkuffka/vue-medium-editor#40]
Hey,

I'm following the guide but I get the error mentioned in the title.

Vue 2.1.10

```
<editor
    :text="text"
    @edit="text = $event"
></editor>
```

```
import Editor from 'vue2-medium-editor'

components: {
    Editor
}
```

**Comment by janwirth** [comment]
I can reproduce it. Looking into it now.

**Comment by janwirth** [comment]
please try out vue2-medium-editor@1.0.6 and tell me if it works for you now :) The package was misconfigured and now I'm using webpack to build the library instead of browserify.
