### ISSUE TITLE
Error DOMException in v1.0.6

### ISSUE THREAD

**Issue by JeanBarriere** [FranzSkuffka/vue-medium-editor#41]
Hi,

I currently have an issue with version `1.0.6`.
The module worked in version `1.0.4` but after update, I have the following error:
```js
Blocked a frame with origin "http://url" from accessing a cross-origin frame
```

I went back to version `1.0.4` for now.
Does anybody have a similar issue ?

Sincerely

**Comment by janwirth** [comment]
Hey, are you using rawgit for the plugin? That's the source that could produce an error like that I think.

**Comment by JeanBarriere** [comment]
Hi, no i use npm and the default vue-cli webpack templates to build my project

**Comment by janwirth** [comment]
can you give a minimal reproduction example?

**Comment by janwirth** [comment]
Did you resolve it / make any progress on this?

**Comment by janwirth** [comment]
Closing as cannot reproduce.
