### ISSUE TITLE
v1.0.6 edit event returning an Object

### ISSUE THREAD

**Issue by hfalucas** [FranzSkuffka/vue-medium-editor#42]
vue: v2.3.4
vue2-medium-editor: v1.0.6
node: v8
webpack.mix (_Laravel built in builder script_): v0.*

```
let mix = require('laravel-mix');
const BabiliPlugin = require('babili-webpack-plugin');
const webpackConfig = { plugins: [] };

mix.js(path, path).sass(path, path)

if (mix.config.inProduction) {
    webpackConfig.plugins.push(new BabiliPlugin());
    mix.options({uglify: false});
    mix.version();
}

mix.webpackConfig(webpackConfig);
```
What is the new api for the version 1.0.6?
I have the component installed as show in the docs:

```
<template>
<editor :text="text" :options="options" @edit="applyEditText"></editor>
</template

<script>
export default {
    data () {
        text: '',
        options: {...}
    },

    methods: {
         applyEditText (text) {
             this.text = text
         }
    }
}
</scritp>
```
In my editor div I'm getting the following error: `Invalid prop: type check failed for prop "text". Expected String, got Object.`

If I console.log the `text` param from the `applyEditText` function I get the following object: `Object {event: Event, api: MediumEditor}` instead of a string like i was getting with v1.0.4

I can't seem to figure out where I can get back the text from the editor.

Can you help me?

Cheers,
Helder

PS: When run the production build script there's this error: 
`Uncaught TypeError: t.extensions.button.extend is not a function`
Dunno if this is related to your package or the main medium-editor

**Comment by janwirth** [comment]
This is indeed intended behaviour, but I forgot updating the docs. I am very sorry. The API change is supposed to make things more flexible. Instead of creating an event / api for every single interaction like getting the caret position, I decided to expose the internal mediumEditor object as well as the Event.

The build script error I have never seen before.

Action Points
- Update Docs
- Release 1.1.0
