### ISSUE TITLE
Changing options dynamically

### ISSUE THREAD

**Issue by dmattia** [FranzSkuffka/vue-medium-editor#45]
I have a computed property that returns one of two objects: one with a toolbar and one without.  I can verify that this computed property changes back and forth between the two objects, but the editor always keeps the same configuration as when the page originally loaded.

```
medium-editor(
    :text="post.title",
    v-if="post.title",
    :options="mediumEditorOptions",
    v-on:edit="updateTitle",
    :reuse-medium-editor-instance="false",
    custom-tag="h3",
)
```

`mediumEditorOptions` is the computed property that is changing

**Comment by janwirth** [comment]
Hey there! Thanks for tuning in :)

This no bug but the feature is not implemented yet.
We would have to add a watcher at https://github.com/FranzSkuffka/vue-medium-editor/blob/master/index.js#L68.
This watcher should apply the changes to `this.api` and boom :boom: done I guess.

PR is welcome! :D

**Comment by dmattia** [comment]
PR created here: https://github.com/FranzSkuffka/vue-medium-editor/pull/46

Let me know your thoughts!

**Comment by janwirth** [comment]
Hey, I commented on your PR. Waiting for your response.

**Comment by janwirth** [comment]
Closing because discussion is continued in #46
