### ISSUE TITLE
Unexpected token import

### ISSUE THREAD

**Issue by wcarron27** [FranzSkuffka/vue-medium-editor#5]
I tried installing your vue2-medium-editor. Unfortunately, following your directions, I've been hit with the error: unexpected token import. It references this code in the dev console:

`import MediumEditor from 'medium-editor'`

Would greatly appreciate any help on figuring this out.

**Comment by dsampaolo** [comment]
This package is a "simple" wrapper for medium-editor.
Did you try to `npm i --save medium-editor` ?

**Comment by wcarron27** [comment]
Closing
Reason: I actually wanted a more traditionally styled rich text editor and found one that more fit my needs. Switched tacks to that, negating the need for this.

Obviously this isn't a knock on your code. Hope it continues to gain steam and progress. Cheers.

**Comment by smyth64** [comment]
I have the same problem 'unexpected token "import"' =/
