### ISSUE TITLE
How to I emit Blur and Focus events?

### ISSUE THREAD

**Issue by jonathanheron** [FranzSkuffka/vue-medium-editor#52]
Hi,

Is there any way to emit the Medium Editor's `blur` and `focus` events from Vue Medium Editor instances?

**Comment by janwirth** [comment]
Hey!

In the latest version, VueMediumEditor emits the `api` of MediumEditor within the event object.
I think you can look into #37, which this ticket duplicates and #51 which this tickets relates to.

**Comment by jonathanheron** [comment]
Thank you @FranzSkuffka

**Comment by jonathanheron** [comment]
@FranzSkuffka I had a look at #37 and that ticket (if I understand it correctly) is a request to trigger the blur event on Medium Editor. What I'm looking to do emit blur events from Vue Medium Editor when Medium Editor emits a blur event.

In Vue Medium Editor, this block of code: https://github.com/FranzSkuffka/vue-medium-editor/blob/d362718e40ece7466fca65dc39218f6bd6bcf2d7/dist/vueMediumEditor.js#L7974-L7979

…emits "edit" events in Vue as expected.

I tried adding: 

```
this.emit = event => this.$emit('blur', {event, api: this.api})
this.api.subscribe('blur', this.emitBlur)
```

…but no blur events fire.

I'm able to subscribe to most or all of the other Medium Editor events successfully. Only `blur` and `focus` do not work.

When I use `editor.subscribe('focus', emitFocus)` with a vanilla version of Medium Editor, it works perfectly.

Do you have any idea what the issue might be?

**Comment by janwirth** [comment]
@jonathanheron I can successfully listen to the events from within the integration - I did not check if the re-emission works. Can you take a look at my demo and tell me where exactly in the chain the events are swallowed / stuck?

https://github.com/FranzSkuffka/vue-medium-editor/tree/52-blur-focus-event-emission

`cd example; yarn; npm start;`

**Comment by jonathanheron** [comment]
![giphy-downsized](https://user-images.githubusercontent.com/394524/29750601-50c3f0a6-8b3a-11e7-9b67-c04fda3b2805.gif)


I'm sorry. There's no issue at all with Vue Medium Editor. I tried your demo and it worked perfectly. 

Then I tried again with what I was testing previously and noticed this

<img width="762" alt="screen shot 2017-08-27 at 15 05 41" src="https://user-images.githubusercontent.com/394524/29750554-8ee9c0b4-8b39-11e7-9cb6-d07624fab2ec.png">

I was rendering the body tag weirdly in my own test. And because the body tag was the same size as the editor, there was no way to properly register the blur.

Sorry for wasting your time 😐

**Comment by jonathanheron** [comment]
A quick follow up. There is a problem with emit events that I don't know how to resolve…

If there are two editors active, events are emitted in duplicated:

![multiple editors](https://user-images.githubusercontent.com/394524/29751423-18277b9a-8b45-11e7-8740-7851666cb674.gif)

**Comment by janwirth** [comment]
![no problem](https://media.giphy.com/media/1iUZeQcC0CmI3yBq/giphy.gif)

@okneloper we are binding a single component to a single instance, right? Maybe MediumEditor is emitting in all of it's instances and each of our components then re-emits...

@jonathanheron Do you do the binding inside the vue2-medium-editor source code or inside the app that is the editor?

**Comment by pizzot** [comment]
Hi All,

Looking at the code at current master, each instance of the component should have it's own MediumEditor. Earlier versions have one root instance that all editors are added to. 

The former should produce instance-specific events, the latter would have common events. @jonathanheron what version are you using?

I am also pretty sure I saw an option along the lines of `reuseEditorInstance` that controlled this behaviour, but I can find it now anymore ¯\_(ツ)_/¯

**Comment by janwirth** [comment]
We removed the `reuseEditorInstance` feature to simplify the structure and clean handling of options changing during runtime.

**Comment by janwirth** [comment]
@jonathanheron - are you blocked or did you do any further analysis?

**Comment by jonathanheron** [comment]
Adding `:reuse-medium-editor-instance="false"` solved my double event problems. Thanks.

**Comment by janwirth** [comment]
@jonathanheron Great! - I assume you are using 1.0.x?

**Comment by jonathanheron** [comment]
@FranzSkuffka yes. Thanks for all your help?
