### ISSUE TITLE
module is duplicated using async import

### ISSUE THREAD

**Issue by gh67uyyghj** [FranzSkuffka/vue-medium-editor#56]
Hello, I use vue2-medium-editor in many components of my app, my issue is

when I split the code using [aync import](https://webpack.js.org/guides/code-splitting/#dynamic-imports) functions to load some of my components, many of the resulting chunks still import separately the same module, see the Webpack bundle analyzer below
![uyu_](https://user-images.githubusercontent.com/13534639/31588546-28391ccc-b1fc-11e7-968b-48e55768eedc.png)
since Medium editor is already too big, I can't make any of code splitting

I am not sure if this is a bug or something is wrong with my webpack config, but this is the only module that is duplicated in chunks

**Comment by janwirth** [comment]
Apparently all your modules except the main module depend on vme.
It is perfectly logical that all your modules contain vme to ensure correct functioning without the other modules. If the parent module does not have the resource, where should the child get the vme module from apart from its own bundle?
I believe that if you import vme in your main file, it will not be in the other bundles.

**Comment by gh67uyyghj** [comment]
Thank you, it seems I just don't really understand how webpack works internally very well

**Comment by janwirth** [comment]
Did this solve it for you? My argument did not have to do with webpacks implementation details - it was just logical reasoning but I could be wrong.

**Comment by gh67uyyghj** [comment]
yes it's solved :D, not what I exactly wanted but I should spend more time trying to understand webpack more
just copying `import VueMediumEditor from 'vue2-medium-editor'` in my entry file, makes the module loaded once in the main output file, I actually wanted to loaded it in the chunks but I will figure that out later

**Comment by janwirth** [comment]
Why do you want it loaded in chunks when you need it in every chunk anyways? :)

**Comment by janwirth** [comment]
@gh67uyyghj - I think this is what you want:
https://webpack.js.org/plugins/commons-chunk-plugin/ 

This will allow you to separate the dependencies from your index file while only loading it once.
