### ISSUE TITLE
how to add medium.js plugins?

### ISSUE THREAD

**Issue by nerminba** [FranzSkuffka/vue-medium-editor#58]
I need plugins for setting text front and background colors. Somebody wrote a plugin for this actually for Medium.js but how do I plug them in considering I am using this vue wrapper by Frank for Medium.js editor. What do I need to modify? Should I fork this package and then in my fork make modifications to include the plugins or is there simpler way to do that?

**Comment by janwirth** [comment]
https://github.com/FranzSkuffka/vue-medium-editor#custom-buttons-and-extensions
