### ISSUE TITLE
how do I set editor mode?

### ISSUE THREAD

**Issue by nerminba** [FranzSkuffka/vue-medium-editor#59]
In the example here: http://jakiestfu.github.io/Medium.js/docs/#demos

they show this piece of code:

new Medium({
    element: document.getElementById('title'),
    mode: Medium.inlineMode,
    maxLength: 25,
    placeholder: 'Your Title'
});

I need to set the mode, how do I do that?

is it something like this:

                mediumEditorOptions: {
                    toolbar: {buttons: ['bold', 'italic', 'strikethrough', 'anchor', 'h1', 'h2', 'h3', 'h4']},
                    mode: Medium.inlinemode,
                },

but how do I access Medium object?

**Comment by nerminba** [comment]
I've tried this:

                mediumEditorOptions: {
                    toolbar: {buttons: ['bold', 'italic', 'strikethrough', 'anchor', 'h1', 'h2', 'h3', 'h4']},
                    mode: VueMediumEditor.MediumEditor.inlinemode,
                    maxLength: 25,
                },


I get no errors but neither mode nor maxLength are applied to the medium editor. Any idea how to do this?

**Comment by janwirth** [comment]
Just pass your options as an attribute to the components.

```
<medium-editor :text='myText' :options='options' custom-tag='h2' v-on:edit='applyTextEdit'>
```

Please read the docs. They really are not that exhaustive.

**Comment by nerminba** [comment]
Hi Frank

I asked here because I read the docs, I know how to set the options, but nowhere in the example you showed above does it show how to set the mode?

**Comment by nerminba** [comment]
this does not work:

       <vue-medium-editor :text='blockContent' custom-tag='div' :options="mediumEditorOptions" v-on:edit='updateBlockContent'></vue-medium-editor>               

       mediumEditorOptions: {
              toolbar: {buttons: ['bold', 'italic', 'strikethrough', 'anchor', 'h1', 'h2', 'h3', 'h4']},
              mode: VueMediumEditor.MediumEditor.inlinemode,
              maxLength: 25,
       },

If I am initializing it wrong then please let me know. If not then we have a bug and you should reopen this issue.

**Comment by janwirth** [comment]
```
const options = mediumEditorOptions

// component script
new Vue {
  ...
  data: () => { options }
  components: {
    'medium-editor': editor
  }
}

<!-- component markup -->
<medium-editor :text='myText' :options='options' custom-tag='h2' v-on:edit='applyTextEdit'>
```

**Comment by nerminba** [comment]
You assume I have no clue what I am doing, so you give me basic vue example above, I appreaciate that :) 

But here is little more detail what I am doing. I am building a complex app in Vue. I do not need the simple example you posted above. 

I am reporting to you right now that when I try to set mode and maxLength like this:

    mediumEditorOptions: {
          toolbar: {buttons: ['bold', 'italic', 'strikethrough', 'anchor', 'h1', 'h2', 'h3', 'h4']},
          mode: VueMediumEditor.MediumEditor.inlinemode,
          maxLength: 25,
    },

it does not work. If you are telling me that code I have posted above should work, then we have a bug. Can we work together so that we debug this or not?

**Comment by nerminba** [comment]
here is parts of some of my code:


        components: {
            Modal,
            VueMediumEditor,
            Markdown,
        },



I am using vue file components. so inside template I have this:

    <vue-medium-editor :class="settings.contentClass" :text='blockContent' custom-tag='div' :options="mediumEditorOptions" v-on:edit='updateBlockContent'></vue-medium-editor>

options are inited like this:

        data: function data() {
            return {
                blockContent: this.$store.getters.itemContent(this.uniqueId),

                mediumEditorOptions: {
                    toolbar: {buttons: ['bold', 'italic', 'strikethrough', 'anchor', 'h1', 'h2', 'h3', 'h4']},
                    mode: VueMediumEditor.MediumEditor.inlinemode,
                    maxLength: 25,
                },

And when I test the editor on the page, I am not experiencing the inlinemode, nor length being limited to 25.

**Comment by janwirth** [comment]
Please, provide a minimum reproduction example using the `/example` directory.

**Comment by nerminba** [comment]
Thanks Franz, will try to put a demo together asp.

**Comment by janwirth** [comment]
Thank you, that makes debugging much easier. I'm willing to inspect all the issues but the preparation is up to you.

BTW, my name is Jan :D

**Comment by nerminba** [comment]
Jan

trying to create the example you can take a look at I get stuck here:

<img width="779" alt="medium" src="https://user-images.githubusercontent.com/443080/32147845-e12e0f8e-bced-11e7-9266-a10c9e32b3e3.png">

it complains about NODE_ENV. 

All my other vue apps are compiling just fine. What am I missing here? Help me move forward so I can provide you with code to replicate the bug above.

**Comment by nerminba** [comment]
I've finished the example for you, you can check out the code from my fork here:

https://github.com/iwebnaut/vue-medium-editor

also example is pretty simple, I've also made a video for you if you want to take a look to see it in action:

https://www.youtube.com/watch?v=YL6B67QEeLg

**Comment by janwirth** [comment]
Did some analysis
1. The options are not applied correctly.
2. The MediumEditor does not expose inlineMode.

**Comment by nerminba** [comment]
I made placeHolder working, is there anything that can be done about inlineMode and maxLength?

**Comment by janwirth** [comment]
How did you get it to work?

**Comment by nerminba** [comment]
like this:

                mediumEditorOptions: {
                    toolbar: {buttons: ['bold', 'italic', 'strikethrough', 'anchor', 'h1', 'h2', 'h3', 'h4', 'indent', 'outdent', 'orderedlist', 'unorderedlist', 'justifyLeft', 'justifyCenter', 'justifyRight']},
                    buttonLabels: 'fontawesome',
                    mode: VueMediumEditor.MediumEditor.inlinemode,
                    maxLength: 25,
                    placeholder: {
                        text: 'Get creative, write something here!',
                        hideOnClick: true
                    }
                },

that works, so now only maxLengt and mode are needed for me to get this as i need it :) how much work is it to get that working?

**Comment by janwirth** [comment]
What exactly is the difference to the code snippet in #60? I am observing some strange behaviour and can not quite figure out it's nature.

**Comment by nerminba** [comment]
can you clarify this: What exactly is the difference?

I belive inlinemode is that you can not break to next line, atleast that is how it behaves in the demo I linked to and in that demo they sat the mode to inlineMode and maxLength to 25 charaters. 

I need exactly that for a component I am making, since you made a wrapper for medium I am confused why medium does not recoqnize these options.

**Comment by janwirth** [comment]
I updated my comment. I am also trying to figure out why exactly the options are not applied... Still inspecting.

**Comment by nerminba** [comment]
Great, I hope we can figure this out as Medium is what I want to use in my project and I need to be able to access all of its features through your wrapper :)

**Comment by janwirth** [comment]
You know what - I think I know the problem. 

We used the wrong documentation... 🙈 
http://jakiestfu.github.io/Medium.js/ is not the same as https://yabwe.github.io/medium-editor/

This plugin is integrating the latter.

So maybe try if you can find what you are looking for in the correct docs ^^ https://github.com/yabwe/medium-editor/blob/master/OPTIONS.md

If you check out the `1.0` you can see the i used medium.js there, but this one here is different xD

Regards

**Comment by nerminba** [comment]
got dam you are right, feel so foolish now :)

**Comment by janwirth** [comment]
All good :)
