### ISSUE TITLE
Uglify cannot handle the "impure helper" 

### ISSUE THREAD

**Issue by dsampaolo** [FranzSkuffka/vue-medium-editor#6]
Hello, 

Me again.

I'm using Laravel-Elixir to transpile and compress/minify my app. Looks like Uglify is not able to parse your code. I could successfully replace the helper function by a method, by copy/pasting the helper into a `methods: {}` section (same level as `mounted() {}`) and replacing the call to `replaceElementWith` (line 20) by `this.replaceElementWith`, and it did the trick.

Uglify still can't parse the code, but it seems to be related to medium-editor and not to your package. 

I'll be glad to submit a PR if you wish :)

**Comment by janwirth** [comment]
PRs are very welcome :) Thank you very much.

**Comment by janwirth** [comment]
@dsampaolo did you try excluding medium-editor from uglify?

I would like to reproduce this issue. Can you give me the specific steps / an example? :) thanks!

**Comment by janwirth** [comment]
Closing this for now.

**Comment by javisperez** [comment]
After debugging this (as I'm having the same exact error) turns that Uglify doesn't support some ES6 syntax, so, the recommended solution to me was to add `"uglify-js": "github:mishoo/UglifyJS2#harmony"` to my package.json which supports es6+

Hope this helps somebody.

**Comment by janwirth** [comment]
Thank you for updating us on this issue :) Appreciated.
