### ISSUE TITLE
customClassOption doesn't work

### ISSUE THREAD

**Issue by hackuun** [FranzSkuffka/vue-medium-editor#67]
I was following official examples, but `customClassOption` doesn't work for some reason

```js
options: {
        toolbar: {
          buttons: [
            'bold',
            'strikethrough',
            'anchor'
          ]
        },
        anchor: {
          customClassOption: 'wtf'
        }
      }
```

**Comment by janwirth** [comment]
Please provide more data.
- which docs
- reproduction example
- actual and expected behaviour

Thank you.

See
https://github.com/FranzSkuffka/vue-medium-editor/blob/master/ISSUE_TEMPLATE.md

**Comment by hackuun** [comment]
@FranzSkuffka 

1. Official Docs https://github.com/yabwe/medium-editor#anchor-form-options
2. Just a basic usage.
3. I was expected to use custom classes added to markup.

**Comment by janwirth** [comment]
Well - this option will make mediumEditor show a button rather than adding the class right away. Please checkout example and next time provide a reproduction example before reporting a bug that is no bug.
