### ISSUE TITLE
When used with vue-at, the edit event could not be captured

### ISSUE THREAD

**Issue by brynne8** [FranzSkuffka/vue-medium-editor#68]
I try to use vue-medium-editor with [vue-at](https://github.com/fritx/vue-at). When the text is updated, no edit event was emitted, and so I couldn't update the content.

**Comment by janwirth** [comment]
Did you miss
# If you are reporting a bug, please provide a minimal working example.
See the `/example` directory

**Comment by janwirth** [comment]
I can't tell if it's a bug or an enhancement request.

**Comment by brynne8** [comment]
```vue
<template>
<div class="text">
    <at :members="friendlist" name-key="nickname">
        <medium-editor
            :text='content'
            v-on:edit='applyTextEdit' />
    </at>
</div>
</template>
<script>
import At from 'vue-at'
import editor from 'vue2-medium-editor'
export default {
    data () {
        return {
            content: '',
        };
    },
    methods: {
        applyTextEdit (ev) {
          this.text = ev.event.target.innerHTML
        },
    },
    components: {
        At,
        'medium-editor': editor
    }
}
</script>
```

**Comment by janwirth** [comment]
I'm not even sure if this can be done.

**Comment by brynne8** [comment]
Actually I made a small hack to use vue-at, as vue-at emits an `at` event and thus I could handle the case.

But in my experience, changes that made to DOM may not be captured by the `editableInput`, therefore couldn't be handled directly.

**Comment by janwirth** [comment]
Would you mind sharing this hack?

**Comment by janwirth** [comment]
Will close if this stays inactive.
