### ISSUE TITLE
Make GitHub releases side-by-side with npm releases

### ISSUE THREAD

**Issue by Skeen** [FranzSkuffka/vue-medium-editor#72]
This is not a bug report, but rather a feature request.

To make it easier to work with specific npm version via. this git repository, it would be lovely, if there were corresponding git-releases or tags for every npm release.

**Comment by janwirth** [comment]
Like this?
https://github.com/FranzSkuffka/vue-medium-editor/releases/tag/1.1.2

**Comment by Skeen** [comment]
Yes exactly :)

**Comment by janwirth** [comment]
Cool - Will try to remember it 🙈

**Comment by janwirth** [comment]
New release for you :) 1.1.3
