### ISSUE TITLE
toolbar not work inside iframe

### ISSUE THREAD

**Issue by lionhurt** [FranzSkuffka/vue-medium-editor#74]
my issue is the same as here : https://github.com/yabwe/medium-editor/issues/183

I use elementsContainer option to add the toolbar in the iframe and add the CSS files inside the iframe window the only problem is the active toolbar never showing 

any ideas?

**Comment by joshuatf** [comment]
+1

**Comment by janwirth** [comment]
Please provide a minimal working example. Otherwise I can't debug.

Generally, the dependencies' issues can't be resolved here but I'm willing to look into it if you provide the _minimum working example_.

**Comment by lionhurt** [comment]
@FranzSkuffka 
Thank you so much for the fast reply. I found the solution from meduim-editor options 

@joshuatf 
here is the solution : 
```
options: {
//toolbar options ....
contentWindow: document.getElementById('my-iframe-id').contentWindow,
ownerDocument: document.getElementById('my-iframe-id').contentWindow.document,
elementsContainer: document.getElementById('my-iframe-id').contentWindow.document.body
}
```

**Comment by joshuatf** [comment]
@lionhurt Awesome- thanks!  Missed those first 2 properties

**Comment by janwirth** [comment]
Apparently it's resolved :) Please bump for reopen in case I'm wrong.
