### ISSUE TITLE
use focus event

### ISSUE THREAD

**Issue by XavRsl** [FranzSkuffka/vue-medium-editor#75]
Hi!

Is there any way to listen to the focus event fired by the medium editor? I see there is support for editableInput but no other event.

thanks!

**Comment by janwirth** [comment]
Sorry for the super-late response. Please check out #76 for a more generic approach to events :)

**Comment by janwirth** [comment]
Check #77 you should be able to subscribe to api events directly.

**Comment by XavRsl** [comment]
Thanks  !!!
