### ISSUE TITLE
Feature request: Emit event after editor is created.

### ISSUE THREAD

**Issue by eric-addcream** [FranzSkuffka/vue-medium-editor#76]
I would like a simple $emit at the end of `createAndSubscribe`.
This feature would provide easier access to the MediumEditor instance without accessing this.$children.

Example:
I'd like to subscribe to some events from MediumEditor. To do this now I would have to access this.$children[index].api with the correct index. This can easily become messy if it's within a v-for with conditions.
By adding an event after the editor is created, I can simply subscribe as soon the editor is created.

Suggested change:
Add the following line at the end of createAndSubscribe. Event name can be anything you see fit.
```javascript
this.$emit('createdEditor', this.api);
```

This would allow developers to do something like this
```html
<medium-editor @createdEditor="(api) => { myEditorSetup(api); }"></medium-editor>
```
```javascript
  myEditorSetup(api) {
    api.subscribe("editableKeydownEnter", this.onMyEditorEnter);
  }
```

**Comment by janwirth** [comment]
Hey there - thank you for the feedback.

Very useful approach you are suggesting there :)

This is related to #75 - Can you carve out a PR?

**Comment by janwirth** [comment]
Published

**Comment by tnylea** [comment]
Does this code:

```javascript
myEditorSetup(api) {
    api.subscribe("editableKeydownEnter", this.onMyEditorEnter);
  }
```

go in the `methods` block? Trying to get this to work, but no luck yet.

Any inside would be greatly appreciated 👍

**Comment by janwirth** [comment]
It should work like this. It also looks fine judging by the API docs.
https://github.com/yabwe/medium-editor/blob/9156a11407451c0ee2e30d971798d6476de4d354/CUSTOM-EVENTS.md#mediumeditor-custom-events-v500

**Comment by tnylea** [comment]
Thanks for the response 👍 I got it. Had to use:

```@editorCreated``` as opposed to `createdEditor`, just had to read through a few of the examples :)
