### ISSUE TITLE
Why not publish sources ?

### ISSUE THREAD

**Issue by partikule** [FranzSkuffka/vue-medium-editor#78]
I perhaps miss something, but I can't see any sources but only the dist folder.

Is it normal ?

**Comment by janwirth** [comment]
The source is both public on NPM and github.
https://github.com/FranzSkuffka/vue-medium-editor/blob/master/index.js

![screen shot 2018-03-11 at 17 56 58](https://user-images.githubusercontent.com/7485959/37256045-a67b04de-2555-11e8-9df0-1c56a15e2491.png)

**Comment by janwirth** [comment]
There's even published too much - actually only `index`, `readme`, `package` and `dist` should be on npm.

**Comment by partikule** [comment]
I agree, but I was speaking about github, not NPM...

To be more clear : 
- How to have a look at the source of your code?
- How to propose you some code correction?

About NPM, we also have some repos on Github. We prepare then separately for NPM.

**Comment by partikule** [comment]
Holly s... I didn't have a look at index.js...was expecting the '"src" folder.

My apologies...
