### ISSUE TITLE
Toolbar buttons doesn't update dynamically

### ISSUE THREAD

**Issue by basselAhmed** [FranzSkuffka/vue-medium-editor#91]
# Are you reporting a bug? Yes

- What is the expected behavior?
A: Toolbar buttons should update dynamically by changing the options.
- What is the actual behavior?
A: Doesn't update.

Please check this sandbox
https://codesandbox.io/s/n59pxx20pp

**Comment by janwirth** [comment]
Hey there.

Thanks for reporting. Can you carve out the time to file a PR?

Investigation needs to be done around this line:
https://github.com/FranzSkuffka/vue-medium-editor/blob/master/interactive.js#L61

Maybe you can fix this using the code from the `example` dir.

**Comment by basselAhmed** [comment]
@FranzSkuffka 
Sure, it seems the watcher doesn't run until we swap the whole options object with a new one.
investigating more on how should we solve this
